EDUH-1.2
DimaSzZ/EduHub.Learn pull request #2
Opened 2024-05-09 17:33 UTC by DimaSzZ

Спроектировал 3/4 юнит теста.

2024-05-17 19:53 UTC, 1nsanov commented
- Не верный формат документации: Используем для классов и методов summary комментари, также есть практика каждый блок Arrange, Act, Assert выделять комментариями // Arrange, // Act, // Assert. Остальные комментарии излишни, если они не оправданы
- Проект с тестами назван некорретно, выбивается из стиля

2024-05-17 20:08 UTC, 1nsanov requested changes

2024-05-17 20:08 UTC, 1nsanov commented on src/Services/StudentService/Tests/Unit/Unit.csproj
> +        <Nullable>enable</Nullable>
Отключить nullable

2024-05-17 20:08 UTC, 1nsanov commented on src/Services/StudentService/Tests/Unit/Tests/Courses/CoursePositiveTests.cs
> +        private readonly DateOnly _minBirthDate = new DateOnly(1900, 1, 1); // Минимальная дата для генерации случайных дат (не используется)
Нигде не используется

2024-05-17 20:08 UTC, 1nsanov commented on src/Services/StudentService/Tests/Unit/Tests/Courses/CoursePositiveTests.cs
> +    public class TestCourseDataClass : IEnumerable<object[]>
Это должно находится в отдельном файле

2024-05-17 20:08 UTC, 1nsanov commented on src/Services/StudentService/Tests/Unit/Tests/Educators/EducatorPositiveTests.cs
> +    public class TestEducatorDataClass : IEnumerable<object[]>
Это должно находится в отдельном файле

2024-05-17 20:08 UTC, 1nsanov commented on src/Services/StudentService/Tests/Unit/Tests/Educators/EducatorPositiveTests.cs
> +        private Gender GetRandomNonDefaultGender()
Можно вынести и использовать данный метод везде для заполнения Gender. Можно написать проще

2024-05-17 20:08 UTC, 1nsanov commented on src/Services/StudentService/Tests/Unit/Tests/Enrollments/EnrollmentPositiveTests.cs
> +    public class TestEnrollmentDataClass : IEnumerable<object[]>
Это должно находится в отдельном файле

2024-05-17 20:08 UTC, 1nsanov commented on src/Services/StudentService/Tests/Unit/Tests/Students/StudentPositiveTests.cs
> +    public class TestStudentDataClass : IEnumerable<object[]>
Это должно находится в отдельном файле

2024-05-17 20:08 UTC, 1nsanov commented on src/Services/StudentService/Tests/Unit/Tests/Students/StudentPositiveTests.cs
> +        private Gender GetRandomNonDefaultGender()
Также, как и в TestEducatorDataClass

2024-05-17 20:08 UTC, 1nsanov commented on src/Services/StudentService/Tests/Unit/Tests/Educators/EducatorPositiveTests.cs
> +            educator.Phone.Should().NotBeNull().And.BeOfType<Phone>(); // Проверка, что Phone не null и имеет тип Phone
Зачем проверка на тип?

2024-05-17 20:08 UTC, 1nsanov commented on src/Services/StudentService/Tests/Unit/Tests/Students/StudentPositiveTests.cs
> +            student.Email.Should().NotBeNull().And.BeOfType<Email>(); // Email не должен быть null и должен быть типа Email
Зачем проверка на тип?

2024-05-17 20:08 UTC, 1nsanov commented on src/Services/StudentService/Tests/Unit/Tests/Students/StudentPositiveTests.cs
> +            student.Phone.Should().NotBeNull().And.BeOfType<Phone>(); // Phone не должен быть null и должен быть типа Phone
Зачем проверка на тип?

2024-05-17 20:08 UTC, 1nsanov commented on src/Services/StudentService/Tests/Unit/Tests/Students/StudentPositiveTests.cs
> +            Gender updatedGender = _faker.Random.Enum<Gender>();
Может сгенерировать значение Default

2024-05-17 20:08 UTC, 1nsanov commented on src/Services/StudentService/Tests/Unit/Tests/Students/StudentPositiveTests.cs
> +            student.Email.Should().NotBeNull().And.BeOfType<Email>(); // Email не должен быть null и должен быть типа Email
Зачем проверка на тип?

2024-05-17 20:08 UTC, 1nsanov commented on src/Services/StudentService/Tests/Unit/Tests/Students/StudentPositiveTests.cs
> +            student.Phone.Should().NotBeNull().And.BeOfType<Phone>(); // Phone не должен быть null и должен быть типа Phone
Зачем проверка на тип?

2024-05-17 20:08 UTC, 1nsanov commented on src/Services/StudentService/Tests/Unit/Tests/Courses/CoursePositiveTests.cs
> +        public void SetCourse_WithValidData_ShouldBeEquivalent(
Не вижу смысла в этом тесте, думаю можно убрать

2024-05-17 20:08 UTC, 1nsanov commented on src/Services/StudentService/Tests/Unit/Tests/Courses/CoursePositiveTests.cs
> +        public void UpdateCourse_WithValidData_ShouldBeEquivalent(
Не вижу смысла в этом тесте, думаю можно убрать

2024-05-17 20:08 UTC, 1nsanov commented on src/Services/StudentService/Tests/Unit/Tests/Students/StudentPositiveTests.cs
> +        public void SetStudent_WithSameData_ShouldBeEquivalent(
Не вижу смысла в этом тесте, думаю можно убрать

2024-05-17 20:08 UTC, 1nsanov commented on src/Services/StudentService/Tests/Unit/Tests/Students/StudentPositiveTests.cs
> +        public void UpdateStudent_WithSameData_ShouldBeEquivalent(
Не вижу смысла в этом тесте, думаю можно убрать

2024-05-17 20:08 UTC, 1nsanov commented on src/Services/StudentService/Tests/Unit/Tests/Students/StudentPositiveTests.cs
> +            Address updatedAddress = new Address(_faker.Address.City(), _faker.Address.StreetName(), int.Parse(_faker.Address.BuildingNumber()));
Можно var использовать, можешь применить через Rider на весь проект

2024-05-19 11:56 UTC, 1nsanov requested changes

2024-05-19 11:56 UTC, 1nsanov commented on src/Services/StudentService/Tests/EduHub.StudentService.Tests.Unit/Infrastructure/TestedClass.cs
> +    private static Gender GetRandomNonDefaultGender()
Подобный метод уже есть в отдельном классе

2024-05-20 07:55 UTC, KillerSanss commented on src/Services/StudentService/Tests/EduHub.StudentService.Tests.Unit/Infrastructure/TestedClass.cs
> +                Faker.Date.BetweenDateOnly(MinDate, new DateOnly(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day)),
Мы пытаемся получить дату в прошлом, поэтому проще написать Faker.Date.PastDateOnly();

2024-05-20 08:08 UTC, KillerSanss commented on src/Services/StudentService/Tests/EduHub.StudentService.Tests.Unit/Infrastructure/TestedData/TestStudentDataClass.cs
> +            EnumGenerator.GetRandomNonDefaultGender(),
Зачем для генерации гендера создавать целый метод?

2024-05-20 08:16 UTC, KillerSanss commented on src/Services/StudentService/Tests/EduHub.StudentService.Tests.Unit/Infrastructure/TestedData/EnumGenerator.cs
>  ﻿namespace Unit.Infrastructure.TestedData;
Почему генератор перечисления находится в одной папке с генераторами для сущностей?

2024-05-20 08:35 UTC, KillerSanss commented on src/Services/StudentService/Tests/EduHub.StudentService.Tests.Unit/Tests/Educators/EducatorPositiveTests.cs
>      {
Нет тестирования метода Update у преподавателя.

2024-05-20 08:38 UTC, 1nsanov commented on src/Services/StudentService/Tests/EduHub.StudentService.Tests.Unit/Infrastructure/TestedData/TestStudentDataClass.cs
> +            EnumGenerator.GetRandomNonDefaultGender(),
Можно оставить отдельный метод, но назвать его попроще и написать реализацию через спец. метод Enum() у Faker

2024-05-20 08:42 UTC, KillerSanss commented on src/Services/StudentService/Tests/EduHub.StudentService.Tests.Unit/Infrastructure/TestedClass.cs
>              },
Лишняя запятая.

2024-05-21 10:37 UTC, merged